-- Create database MYDB
CREATE DATABASE IF NOT EXISTS MYDB;
USE MYDB;

-- Create table MyGuests (from create_table.php)
CREATE TABLE IF NOT EXISTS myguests (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    email VARCHAR(50),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);